version: '3.2'
services:
    db:
        image: postgres:10.7
        container_name: db
        hostname: db
        ports:
            - '5435:5432'
        volumes:
            - ./var/lib/postgresql/data:/var/lib/postgresql/data
        env_file:
            - env

    python_app:
        container_name: python_app
        build:
            context: ./python_app
        volumes:
            - ..:/python_app
        ports:
            - '8000:8000'
        env_file:
            - env
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_TYPE=postgresql
            - DEBUG=1
            # - ALLOWED_HOSTS=* localhost
        depends_on:
            - db

# folder permission bug on windows?
# volumes:
#   local_postgres_data: {}
#
# postgres:
#   image: postgres:10.4
#   volumes:
#     - local_postgres_data:/var/lib/postgresql/data
