version: '3.2'
services:
    db:
        image: postgres:10.7
        container_name: db
        hostname: db
        ports:
            - '5435:5432'
        env_file:
            - env
        environment:
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data

    python_app:
        container_name: python_app
        build:
            context: ./python_app
        volumes:
            - ..:/python_app
        ports:
            - '8010:8000'
        env_file:
            - env
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_TYPE=postgresql
            - DEBUG=1
            # - ALLOWED_HOSTS=* localhost
        depends_on:
            - db

volumes:
    pgdata:
        driver: local
